package com.tlv8.v3.flw.mapper;

import java.util.List;
import java.util.Map;

import com.baomidou.dynamic.datasource.annotation.DS;

import org.apache.ibatis.annotations.Mapper;

import com.tlv8.v3.flw.pojo.SaTask;

@DS("system")
@Mapper
public interface SaTaskMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sa_task
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	int deleteByPrimaryKey(String sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sa_task
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	int insert(SaTask row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sa_task
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	SaTask selectByPrimaryKey(String sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sa_task
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	List<SaTask> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sa_task
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	int updateByPrimaryKey(SaTask row);

	/**
	 * 
	 * @param param
	 * @return
	 */
	int cancelOtherTask(Map<String, Object> param);

	/**
	 * 结束流程
	 * 
	 * @param flowID
	 * @return
	 */
	int accomplishFlow(String flowID);

	List<SaTask> selectByFlowID(String flowID);

	List<SaTask> selectByFlowActivity(Map<String, Object> param);

	/**
	 * 获取指定环节其他任务列表（状态）
	 * 
	 * @param flowID
	 * @param activity
	 * @param taskID
	 * @param statusid
	 * @return
	 */
	List<SaTask> selectActivityOtherTask(Map<String, Object> param);
	
	/**
	 * 根据业务ID查询流程信息
	 * @param sdata1
	 * @return
	 */
	List<SaTask> selectProcessByBillID(String sdata1);
}