package com.tlv8.v3.oa.mapper;

import com.baomidou.dynamic.datasource.annotation.DS;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.tlv8.v3.oa.pojo.OaNewsColumn;

@DS("oa")
@Mapper
public interface OaNewsColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int insert(OaNewsColumn row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    OaNewsColumn selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    List<OaNewsColumn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int updateByPrimaryKey(OaNewsColumn row);
}