# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8085
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
    background-processor-delay: 30

# Spring配置
spring:
  application:
    name: tlv8-v3-docserver
    version: 3.4.0
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 数据库配置
  datasource:
    dynamic:
      primary: doc
      datasource:
        doc:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/tlv8-vue?characterEncoding=utf8&useUnicode=true&useSSL=false
          username: root
          password: TLv8MySQL
    hikari:
       #最小空闲连接数量
       minimum-idle: 10
       # 最大连接数
       maximum-pool-size: 100
       #从池返回的连接默认自动提交
       auto-commit: true
       #空闲连接最大时间，10秒
       idle-timeout: 10000
       #池中连接的最长生命周期
       max-lifetime: 1800000
       #数据库连接的超时时间
       connection-timeout: 30000
  # 文件上传
  servlet:
     multipart:
       enabled: true
       # 单个文件大小
       max-file-size:  100MB
       # 设置总上传的文件大小
       max-request-size:  100MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:
    servlet:
      load-on-startup: 1
  #日期类型转换成时间戳返回      
  jackson:
    serialization:
      write-dates-as-timestamps: false
    # 日期类型转换成字符串返回
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    # redis配置 
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: dev.tlv8.com
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: TLv8redisPassHJklttU97y
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token: 
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期 
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    active-timeout: -1
    # token风格
    token-style: random-32
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录) 
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token) 
    is-share: true
    # 是否输出操作日志 
    is-log: false
    
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.tlv8.**.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml